### ISSUE TITLE
Build fails with LLVM/Clang 8/9/10

### ISSUE THREAD

**Issue by ghost** [linnaea/beignet#5] opened 2020-05-23 02:08 UTC
The code builds fine with LLVM/Clang 7, but not with version 8/9/10:
```
FAILED: backend/src/libgbeinterp.so 
: && /usr/bin/clang++ -fPIC -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -funroll-loops -fstrict-aliasing -msse2 -msse3 -mssse3 -msse4.1 -fPIC -Wall -Wno-invalid-offsetof -I/usr/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DGBE_DEBUG_MEMORY=0  -DGBE_COMPILER_AVAILABLE=1 -fvisibility=hidden -O2 -DNDEBUG -DGBE_DEBUG=0  -fuse-ld=lld -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-Bsymbolic -Wl,--no-undefined -L/usr/lib -shared -Wl,-soname,libgbeinterp.so -o backend/src/libgbeinterp.so backend/src/CMakeFiles/gbeinterp.dir/gbe_bin_interpreter.cpp.o   && :
ld.lld: error: undefined symbol: llvm::DisableABIBreakingChecks
>>> referenced by gbe_bin_interpreter.cpp
>>>               backend/src/CMakeFiles/gbeinterp.dir/gbe_bin_interpreter.cpp.o:(llvm::VerifyDisableABIBreakingChecks)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```
[Full build log](https://github.com/linnaea/beignet/files/4670984/log.txt)

**Comment by linnaea** [comment] 2020-05-24 12:21
I myself can build it under [openSUSE Tumbleweed](https://build.opensuse.org/public/build/home:linnaea:Intel-OpenCL/openSUSE_Tumbleweed/x86_64/beignet/_log) so my hunch is that it's some LLVM weirdness.

I can reproduce this on Leap 15.1 with any LLVM version higher than what the base image offers. Not a clue on where the problem lies.

The current situation with LLVM10 is that beignet can compile and link against it, but would miscompile almost everything thrown at it. That includes the benchmark program used by clpeak.

However given that:
- Beignet only targets Gen7-9
- Intel's NEO runtime supports Gen8+ and is a lot better than this mess now (not the case 2 years ago)
- Gen7 and 7.5 (Ivy Bridge and Haswell) is just trash (there's some design choice and chip errata that require software emulation for basic operations, stuff like Saturated Math Instructions not doing saturation properly, jumps being limited to +/-128KiB, no hardware int64 support of any kind)

I'm increasingly leaning towards just giving up supporting newer LLVM and link this mess statically with LLVM 4 or 3.9 or 3.8 and call it a day.

**Comment by ghost** [comment] 2020-05-24 13:07
I am on Braswell (Gen8LP) so I have no choice but to use the deprecated Beignet runtime. Because of the issue with LLVM 8+ (and my Linux distribution uses LLVM/Clang 10), I need to have LLVM and Clang 7 installed to `/opt` to make Beignet usable.

I have opened a [request in intel/compute-runtime](https://github.com/intel/compute-runtime/issues/317) in the hope that they will eventually add support for Gen8LP in NEO.

**Comment by linnaea** [comment] 2020-05-25 07:59
Should be fixed in ff59e2d, still not usable though.

**Comment by ghost** [comment] 2020-05-25 11:10
With [this patch](https://lists.freedesktop.org/archives/beignet/2020-January/009247.html), your code seems usable on LLVM 10.
`john --format=rar-opencl --test` does not crash and `hashcat`produces correct result.

**Comment by linnaea** [comment] 2020-06-19 08:26
Miscompilation seems to only affect pre-Gen8 devices. Closing for now.

That patch shouldn't be necessary as this branch has implemented emulations for funnel shift intrinsics in 5242a6b.

**Closed as completed by linnaea** 2020-06-19 08:26 UTC

**Comment by ghost** [comment] 2020-11-12 03:45
Is there any plan to support LLVM 11?
```
FAILED: backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o 
/usr/bin/c++ -DENABLE_FP64 -DENABLE_OPENCL_20 -DGEN7_SAMPLER_CLAMP_BORDER_WORKAROUND -DLLVM_110 -Dgbe_EXPORTS -I. -I/usr/src/packages/BUILD/beignet/src/beignet -I/usr/src/packages/BUILD/beignet/src/beignet/include -I/usr/include/libdrm -Ibackend -I/usr/src/packages/BUILD/beignet/src/beignet/backend/src/. -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -funroll-loops -fstrict-aliasing -msse2 -msse3 -mssse3 -msse4.1 -fPIC -Wall -mfpmath=sse -Wcast-align -Wl,-E -Wno-invalid-offsetof -I/usr/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DGBE_DEBUG_MEMORY=0  -DGBE_COMPILER_AVAILABLE=1 -fvisibility=hidden -O2 -DNDEBUG -DGBE_DEBUG=0 -fPIC -std=gnu++14 -MD -MT backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o -MF backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o.d -o backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o -c /usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_sampler_fix.cpp
In file included from /usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_sampler_fix.cpp:24:
/usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_includes.hpp:105:10: fatal error: llvm/IR/CallSite.h: No such file or directory
  105 | #include "llvm/IR/CallSite.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by linnaea** [comment] 2020-11-13 02:09
> 
> 
> Is there any plan to support LLVM 11?
> 
> ```
> FAILED: backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o 
> /usr/bin/c++ -DENABLE_FP64 -DENABLE_OPENCL_20 -DGEN7_SAMPLER_CLAMP_BORDER_WORKAROUND -DLLVM_110 -Dgbe_EXPORTS -I. -I/usr/src/packages/BUILD/beignet/src/beignet -I/usr/src/packages/BUILD/beignet/src/beignet/include -I/usr/include/libdrm -Ibackend -I/usr/src/packages/BUILD/beignet/src/beignet/backend/src/. -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -funroll-loops -fstrict-aliasing -msse2 -msse3 -mssse3 -msse4.1 -fPIC -Wall -mfpmath=sse -Wcast-align -Wl,-E -Wno-invalid-offsetof -I/usr/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DGBE_DEBUG_MEMORY=0  -DGBE_COMPILER_AVAILABLE=1 -fvisibility=hidden -O2 -DNDEBUG -DGBE_DEBUG=0 -fPIC -std=gnu++14 -MD -MT backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o -MF backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o.d -o backend/src/CMakeFiles/gbe.dir/llvm/llvm_sampler_fix.cpp.o -c /usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_sampler_fix.cpp
> In file included from /usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_sampler_fix.cpp:24:
> /usr/src/packages/BUILD/beignet/src/beignet/backend/src/llvm/llvm_includes.hpp:105:10: fatal error: llvm/IR/CallSite.h: No such file or directory
>   105 | #include "llvm/IR/CallSite.h"
>       |          ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

Stick to LLVM 9 (or even better, 4) if you can, it produces bad code with LLVM 10.

I have since got rid of my Gen7 hardware (went team red) so the most I can do now is to make it compile with LLVM11, but it would probably still produce bad code.

**Comment by ghost** [comment] 2020-11-23 02:27
> the most I can do now is to make it compile with LLVM11

Yes, please do it if you can. I would like to see if it produces bad code on my Gen8LP hardware.

Intel developers decided that they will not support Gen8LP in NEO, so I am still using your repository for OpenCL.
